web:
  host: ""
  port: ""
  time: ""
script:
  cmdName: ""
  successMsg: ""
model:
  path: ""
  rootPath: ""
  dataPath: ""
  trainPath: ""
  valiPath: ""
  testPath: ""
kafka:
  topic1: ""
  topic2: ""
  finishMsg: ""
jwt:
  token: ""
  issuer: ""
redis:
  addr:  ""
  password: ""
  db: ""
  poolsize: ""
email:
  account: ""
  password: ""
mysql:
  host: ""
  port: ""
  database: ""
  username: ""
  password: ""
  charset: ""
user:
  default: ""
