web:
  host:
  port:
  time:
script:
  cmdName:
  successMsg:
model:
  path:
  name:
  checkpoints:
kafka:
  topic1:
  topic2:
  finishMsg:
  host:
  timeOut:
jwt:
  token:
  issuer:
redis:
  addr:
  password:
  db:
  poolsize:
email:
  account:
  password:
mysql:
  host:
  port:
  database:
  username:
  password:
  charset:
user:
  default:
